// POST /api/runs/{runId}/draft-bug-brief
// Reads the stored debug-capture (or Slack context) observation and drafts a confirmable report (C2).
import { NextRequest, NextResponse } from "next/server";
import { dbInsert, dbSelect, getRun } from "@/lib/insforge/db";
import { setStatus } from "@/lib/insforge/status";
import { draftReportWithLLM, type ReportSlackMessage } from "@/lib/diagnosis/report";
import { shortKey } from "@/lib/ids";
import type {
  BugBriefRow,
  EvidenceSummaryItem,
  ReflexRunRow,
  ReportDraft,
} from "@/lib/insforge/types";

export const runtime = "nodejs";

interface ObservationRow {
  id: string;
  transcript: string;
  visible_state: {
    symptomSeed?: string;
    evidenceSummary?: EvidenceSummaryItem[];
    notes?: string;
    [k: string]: unknown;
  };
}

/**
 * Drafts the confirmable bug report from Slack context or debug-capture observations.
 *
 * @param req Request containing optional draft config.
 * @param params Dynamic route params containing the run ID.
 * @returns Confirmable report draft generated by the LLM path, or scripted fallback without a model key.
 * @sideEffects Inserts a bug_briefs row and appends a report.drafted event in InsForge.
 */
export async function POST(req: NextRequest, { params }: { params: { runId: string } }) {
  const { runId } = params;
  const run = await getRun<ReflexRunRow>(runId);
  if (!run) return NextResponse.json({ error: "run not found" }, { status: 404 });

  const observations = await dbSelect<ObservationRow>(
    "observations",
    `run_id=eq.${runId}&order=created_at.desc&limit=1`
  );
  const obs = observations[0];
  const symptomSeed =
    obs?.visible_state?.symptomSeed ||
    obs?.transcript ||
    run.command_text ||
    "Captured issue";
  const segment = {
    visibleState: obs?.visible_state ?? {},
    evidenceSummary: obs?.visible_state?.evidenceSummary ?? commandEvidence(run.command_text),
    symptomSeed,
  };
  const slackMessages = await dbSelect<ReportSlackMessage>(
    "slack_context_messages",
    `run_id=eq.${runId}&order=created_at.asc&limit=${run.context_window?.messageLimit ?? 100}`
  );

  const fields = await draftReportWithLLM({
    role: run.role,
    repoUrl: run.repo_url,
    segment,
    transcript: obs?.transcript ?? run.command_text,
    notes: obs?.visible_state?.notes ?? run.command_text,
    commandText: run.command_text,
    slackMessages,
    maxPromptChars: run.context_window?.maxPromptChars ?? 6000,
  });

  const brief = await dbInsert<BugBriefRow>("bug_briefs", {
    run_id: runId,
    brief_key: shortKey("brief"),
    where_it_happens: fields.whereItHappens,
    actual_behavior: fields.actualBehavior,
    expected_behavior: fields.expectedBehavior ?? null,
    reproduction_context: fields.reproductionContext ?? null,
    affected_surface: fields.affectedSurface,
    evidence_summary: fields.evidenceSummary,
    missing_info: fields.missingInfo,
    agent_prompt_preview: fields.agentPromptPreview,
    status: "needs_confirmation",
  });

  await setStatus(runId, "report_drafted", {
    eventType: "report.drafted",
    title: "Bug report drafted",
    detail: fields.actualBehavior,
    payload: { bugBriefId: brief.id, symptomSeed },
  });

  const draft: ReportDraft = {
    runId,
    bugBriefId: brief.id,
    status: "needs_confirmation",
    whereItHappens: fields.whereItHappens,
    actualBehavior: fields.actualBehavior,
    expectedBehavior: fields.expectedBehavior,
    reproductionContext: fields.reproductionContext,
    affectedSurface: fields.affectedSurface,
    evidenceSummary: fields.evidenceSummary,
    missingInfo: fields.missingInfo,
    agentPromptPreview: fields.agentPromptPreview,
  };
  return NextResponse.json(draft);
}

/**
 * Builds evidence from slash-command text when Slack history was not available.
 *
 * @param commandText Raw slash command text stored on the run.
 * @returns Evidence summary items for report drafting.
 * @sideEffects None.
 */
function commandEvidence(commandText: string): EvidenceSummaryItem[] {
  const text = commandText.trim();
  return text ? [{ kind: "slack_command", summary: text }] : [];
}
